### PR TITLE
Parse when documenting

### PR DESCRIPTION
**Pull request by Coolroo**
will now parse when documenting

### CODE REVIEW

**Review by calum-bird — CHANGES_REQUESTED** [review]
We still need to update the parsed functions when the window changes for the doc progress bar. Is this accounted for elsewhere?

**Comment by Coolroo** [comment]
> We still need to update the parsed functions when the window changes for the doc progress bar. Is this accounted for elsewhere?

good call! Will look into events that should call this, to see if any were missing from the original implementation

**Comment by calum-bird** [comment]
Sounds good! 

I think architecturally this is a bit flawed right now because I put codeParser as a service, when maybe it should be a "provider". Services can request updates and pull from providers (or the provider just knows when to update in response to events).

This is outside the scope of this branch though, and I think the current approach is okay for now. Eventually we should take a deeper look at the design of the parsing service, though, because I think the confusion here stems from this architecturally.

**Comment by Coolroo** [comment]
Yes I agree, did some tests, the events do fire when changing windows, so I just replaced the ones I deleted

**Review by calum-bird — APPROVED** [review]

**Pull request merged**
